---
# handlers file for deploy_apache_web
- name: restart apache on RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: restart apache on Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
