---
# tasks file for deploy_apache_web
- debug:
    var: ansible_os_family

- block: #---block for RedHat-----
 
    - name: install apache on RedHat
      yum: name=httpd state=latest
    - name: apache start for RedHat
      service: name=httpd state=started
  when: ansible_os_family == "RedHat"

- block: #-----block for debian-----

    - name: install apache on Debian
      yum: name=apache2 state=latest

    - name: apache start for Debian
      service: name=apache2 state=started

  when: ansible_os_family == "Debian"
- name: generate html page
  template: src=index.j2 dest={{dest_dir}}/index.html
  notify:
    - restart apache on RedHat
    - restart apache on Debian
- name: copy web page
  copy: src={{item}} dest={{dest_dir}}
  with_fileglob: "*.*"
