# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch: 
  push:
    branches: 
      - main
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
env:
  APP_NAME: "My App"
  PACKAGE_NAME: "deployment_id_${{github.sha}}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: testing
        run: echo "Hello ${{ github.event.inputs.name }} from testing"
      - name: execute few commands
        run: |
          echo "message1"
          echo "message2"
          echo "app name {{env.APP_NAME}}"
        
  deploy:  
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
      - name: deploy
        run: echo "Hello ${{ github.event.inputs.name }} from deploy"
      - name: print deploy message
        run: echo "deployment name {{env.PACKAGE_NAME}}" 
